CREATE TABLE ALUNO(
	MATRICULA SERIAL,
	NOME VARCHAR(50),
	TURMA INT,
	CPF VARCHAR(11),
	DATA_NASC DATE,
	PRIMARY KEY(MATRICULA)
);

CREATE TABLE TURMA(
	ID SERIAL,
	SERIE VARCHAR(6),
	CURSO INT,
	PERIODO VARCHAR(15),
	PRIMARY KEY(ID)
);

CREATE TABLE CURSO(
	ID SERIAL,
	NOME VARCHAR(50),
	COD_PROFESSOR INT,
	COD_ALUNO INT,
	DURACAO_HORAS INT,
	PRIMARY KEY(ID),
	FOREIGN KEY(COD_ALUNO) REFERENCES ALUNO(MATRICULA)	
);

CREATE TABLE PROFESSOR(
	MATRICULA SERIAL,
	NOME VARCHAR(100),
	FORMACAO VARCHAR(50),
	DATA_NASC DATE,
	CPF VARCHAR(11),
	PRIMARY KEY(MATRICULA)
);

CREATE TABLE NOTA(
	ID_NOTA SERIAL,
	MAT_ALUNO INT,
	COD_DISCIPLINA INT,
	NOTA FLOAT,
	DATA DATE,
	PRIMARY KEY(ID_NOTA),
	FOREIGN KEY(MAT_ALUNO) REFERENCES ALUNO(MATRICULA)
);